[package]
name = "axum_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
tokio = { version = "1", features = ["full"] }
axum-client-ip="0.7.0"
lazy_static="1.5.0"


[[bin]]
name = "axum_server"
path = "src/main.rs"